teacher/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'teacher'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('coursetable/', views.CourseTableView.as_view(), name='coursetable'),
    path('classactive/', views.ClassActive.as_view(), name='active'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('logout-then-login/', auth_views.logout_then_login, name='logou_then_login'),
    path('ask/', views.CustomerAskView.as_view(), name='ask'),
    path('summary/', views.SummaryView.as_view(), name='summary'),
    path('score/<str:banji_name>/<str:scorename>/', views.ClassStudentActScoreView.as_view(), name='score'),
    path('export2excel/<str:banji_name>/<str:scorename>/', views.export_to_excel, name='export2excel'),
]

teacherAssistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teacher.urls', namespace='teacher')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

teacher/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


# Create your models here.
class Banji(models.Model):
    name = models.CharField(max_length=100, verbose_name='班级名')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    banji = models.ForeignKey(Banji, on_delete=models.CASCADE)
    # act = models.ForeignKey(Act, on_delete=models.CASCADE, null=True, blank=True)
    No = models.CharField(max_length=10, verbose_name='学号')
    name = models.CharField(max_length=20, verbose_name='姓名')
    sex = models.CharField(max_length=4, verbose_name='性别')

    def __str__(self):
        return self.name


class Act(models.Model):
    # student = models.ManyToManyField(Student, related_name='joined_act', blank=True)
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                verbose_name='任课教师',
                                null=True, blank=True)
    banji = models.ForeignKey(Banji, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=100, verbose_name='活动题目')
    # score = models.FloatField(default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name='开展时间')

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.title


class StudentActScore(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    act = models.ForeignKey(Act, on_delete=models.CASCADE)
    score = models.FloatField(default=0)


class Course(models.Model):
    name = models.CharField(max_length=100, verbose_name='课程名')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name='课程封面图')

    def __str__(self):
        return self.name


class Schedule(models.Model):
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                verbose_name='任课教师',
                                null=True, blank=True)
    banji = models.ForeignKey(Banji, on_delete=models.CASCADE, verbose_name='班级', null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
    room_name = models.CharField(max_length=100, verbose_name="教室名")
    week = models.CharField(max_length=10, verbose_name="星期几")
    order = models.CharField(max_length=5, verbose_name="第几节")

    class Meta:
        index_together = ['week', 'order']

    def __str__(self):
        return "{}的{}，{}主讲".format(self.banji.name, self.course.name, self.teacher.username)


class Customer(models.Model):
    c_name = models.CharField(max_length=50)
    c_tel = models.CharField(max_length=20)
    c_email = models.EmailField()
    messages = models.TextField()
    is_finished = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.c_name

teacher/forms.py
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['c_name', 'c_tel', 'c_email', 'messages']

teacher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from django.http import JsonResponse, HttpResponse
import time
import random
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment

from .models import Schedule, Student, Act, StudentActScore, Banji
from .forms import CustomerForm


class IndexView(View):
    def get(self, request):
        return render(request, 'teacher/index.html')


class ClassActive(LoginRequiredMixin, View):
    def post(self, request):
        act_name = request.POST.get('act_name')
        banji_name = request.POST.get('banji')
        if request.POST['inlineRadioOptions']=='option1':
            stu_name1 = request.POST.get('name1')
            stu_name2 = request.POST.get('name2')
            stu_name3 = request.POST.get('name3')
            score1 = request.POST.get('score1')
            score2 = request.POST.get('score2')
            score3 = request.POST.get('score3')
        else:
            stu_name1 = request.POST.get('stu1')
            stu_name2 = request.POST.get('stu2')
            stu_name3 = request.POST.get('stu3')
            score1 = request.POST.get('sco1')
            score2 = request.POST.get('sco2')
            score3 = request.POST.get('sco3')

        if act_name and banji_name and stu_name1 and stu_name2 and stu_name3 and score1 and score2 and score3:
            banji = Banji.objects.get(name=banji_name)
            act = Act()
            act.banji = banji
            act.title = act_name
            act.save()

            student1 = get_object_or_404(Student, name=stu_name1)
            student2 = get_object_or_404(Student, name=stu_name2)
            student3 = get_object_or_404(Student, name=stu_name3)


            ss1 = StudentActScore()
            ss1.student = student1
            ss1.act = act
            ss1.score = score1
            ss1.save()

            ss2 = StudentActScore()
            ss2.student = student2
            ss2.act = act
            ss2.score = score2
            ss2.save()

            ss3 = StudentActScore()
            ss3.student = student3
            ss3.act = act
            ss3.score = score3
            ss3.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'fail'})


    # login_url = '/login/'
    def get(self, request):
        courses = Schedule.objects.filter(teacher=request.user)
        ones = courses.filter(order='一')
        twos = courses.filter(order='二')
        threes = courses.filter(order='三')
        fours = courses.filter(order='四')
        fives = courses.filter(order='五')
        sixes = courses.filter(order='六')

        weekday = time.strftime("%w")
        weekdict = {'0': '星期日',
                    '1': '星期一',
                    '2': '星期二',
                    '3': '星期三',
                    '4': '星期四',
                    '5': '星期五',
                    '6': '星期六'
                    }
        today = weekdict[weekday]
        today_courses = courses.filter(week=today)
        today_courses = self.modify_day_courses(today_courses)
        while not any(today_courses):
            weekday = str((int(weekday) + 1) % 7)
            weekdict = {'0': '星期日',
                        '1': '星期一',
                        '2': '星期二',
                        '3': '星期三',
                        '4': '星期四',
                        '5': '星期五',
                        '6': '星期六'
                        }
            today = weekdict[weekday]
            today_courses = courses.filter(week=today)
            today_courses = self.modify_day_courses(today_courses)

        before_course = None
        current = time.strftime('%H')
        if int(current) < 10:
            before_course = today_courses[0]
        elif int(current) < 12:
            part_courses = today_courses[0:2]
            before_course = self.first_no_none(part_courses)
        elif int(current) < 15:
            part_courses = today_courses[0:3]
            before_course = self.first_no_none(part_courses)
        elif int(current) < 17:
            part_courses = today_courses[0:4]
            before_course = self.first_no_none(part_courses)
        elif int(current) < 19:
            part_courses = today_courses[0:5]
            before_course = self.first_no_none(part_courses)
        elif int(current) < 24:
            part_courses = today_courses[:]
            before_course = self.first_no_none(part_courses)

        for cc in today_courses:
            if cc != None:
                first_course = cc
                break
        if before_course == None:
            before_course = first_course

        # 获取当前上课班级的学生名单
        students = Student.objects.filter(banji=before_course.banji)[:]
        # 随机返回
        new_students=[s for s in students]

        students = random.sample(new_students, 3)
        return render(request, 'teacher/classactive.html', {'before_course': before_course,
                                                            'students': students})

    def first_no_none(self, l):
        t = l[::-1]
        for x in t:
            if x:
                break
        return x

    def modify_day_courses(self, ones):
        all_day = [None, None, None, None, None, None]
        for c in ones:
            if c.order == '一':
                all_day[0] = c
            elif c.order == '二':
                all_day[1] = c
            elif c.order == '三':
                all_day[2] = c
            elif c.order == '四':
                all_day[3] = c
            elif c.order == '五':
                all_day[4] = c
            else:
                all_day[5] = c

        return all_day


class CourseTableView(LoginRequiredMixin, View):
    # login_url = '/login/'
    def get(self, request):
        courses = Schedule.objects.filter(teacher=request.user)
        ones = courses.filter(order='一')
        twos = courses.filter(order='二')
        threes = courses.filter(order='三')
        fours = courses.filter(order='四')
        fives = courses.filter(order='五')
        sixes = courses.filter(order='六')

        weekday = time.strftime("%w")
        weekdict = {'0': '星期日',
                    '1': '星期一',
                    '2': '星期二',
                    '3': '星期三',
                    '4': '星期四',
                    '5': '星期五',
                    '6': '星期六'
                    }
        today = weekdict[weekday]
        today_courses = courses.filter(week=today)
        today_courses = self.modify_day_courses(today_courses)

        ones = self.modify_courses(ones)
        twos = self.modify_courses(twos)
        threes = self.modify_courses(threes)
        fours = self.modify_courses(fours)
        fives = self.modify_courses(fives)
        sixes = self.modify_courses(sixes)
        return render(request, 'teacher/coursetable.html', {'ones': ones,
                                                            'twos': twos,
                                                            'threes': threes,
                                                            'fours': fours,
                                                            'fives': fives,
                                                            'sixes': sixes,
                                                            'today_courses': today_courses
                                                            })

    def modify_courses(self, ones):
        all_ones = [None, None, None, None, None, None, None]
        for c in ones:
            if c.week == '星期一':
                all_ones[0] = c
            elif c.week == '星期二':
                all_ones[1] = c
            elif c.week == '星期三':
                all_ones[2] = c
            elif c.week == '星期四':
                all_ones[3] = c
            elif c.week == '星期五':
                all_ones[4] = c
            elif c.week == '星期六':
                all_ones[5] = c
            else:
                all_ones[6] = c
        return all_ones

    def modify_day_courses(self, ones):
        all_day = [None, None, None, None, None, None]
        for c in ones:
            if c.order == '一':
                all_day[0] = c
            elif c.order == '二':
                all_day[1] = c
            elif c.order == '三':
                all_day[2] = c
            elif c.order == '四':
                all_day[3] = c
            elif c.order == '五':
                all_day[4] = c
            else:
                all_day[5] = c

        return all_day


class LogoutView(View):
    def post(self, request):
        logout(request)
        return redirect('teacher:index')


class CustomerAskView(View):
    def post(self, request):
        customerask_form = CustomerForm(request.POST)
        if customerask_form.is_valid():
            customerask_form.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'fail', 'msg': '提交出错了'})


class SummaryView(LoginRequiredMixin, View):
    def get(self, request):

        t_schedules = Schedule.objects.filter(teacher=request.user)
        t_schedules = t_schedules.values('banji__name', 'course__name').distinct()

        return render(request, 'teacher/summaryscore.html', {'t_schedules': t_schedules})


class ClassStudentActScoreView(View):
    def get(self, request, banji_name, scorename):
        banji = get_object_or_404(Banji, name=banji_name)
        scorename=scorename
        students = banji.student_set.all()
        acts = banji.act_set.all()
        acts = acts.filter(teacher=request.user)

        stuactscore=[]
        for stu in students:
            temp = []
            temp.append(stu.No)
            temp.append(stu.name)
            for act in acts:
                try:
                    stuact = StudentActScore.objects.get(student=stu, act=act)

teacher/templates/teacher/index.html
{% extends "base-4.1.1.html" %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}
{% block title %}
    教师个人助理 - 首页
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">洛师电商</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'teacher:index' %}">
                            首页
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'teacher:coursetable' %}">
                            教师课表
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'teacher:active' %}">
                            课堂活动
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'teacher:summary' %}">
                            成绩汇总
                        </a>
                    </li>
                </ul>
                <span class="navbar-text">
                    {% if request.user.is_authenticated %}
                        {{ request.user.username }},
                        <a data-toggle="modal" data-target="#loginModal">
                            退出
                        </a>
                    {% else %}
                    <a href="{% url 'teacher:login' %}">
                        登录
                    </a>
                    {% endif %}
                </span>
            </div>

        </div>
    </nav>
    <div id="loginModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg" role="content">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">退出登录</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'teacher:logout' %}" method="post">
                        <div class="form-group row">

                            <div class="col-sm-10">
                                <p>您将退出登录状态！</p>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12 d-flex justify-content-end">
                                <button type="button" class="btn btn-secondary btn-sm mr-3" data-dismiss="modal">取消</button>
                                <button type="submit" class="btn btn-primary btn-sm mr-3">确定</button>
                            </div>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
    <header class="jumbotron pb-1 pt-1">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="calander" style="padding:15px;">
                        <h2 style="text-align: center;"><span class="year"></span> <span class="month"></span>&nbsp;&nbsp;校历第<span
                                class="week" style="color:blue;"></span> 周 </h2>
                        <table class="table table-sm table-bordered bg-light">
                            <thead>
                            <tr>
                                <th scope="col">日</th>
                                <th scope="col">一</th>
                                <th scope="col">二</th>
                                <th scope="col">三</th>
                                <th scope="col">四</th>
                                <th scope="col">五</th>
                                <th scope="col">六</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                        <script>
                            //判断闰年,如果是返回1， 否则返回0
                            function is_leap(year) {
                                return (year % 100 == 0 ? res = (year % 400 == 0 ? 1 : 0) : res = (year % 4 == 0 ? 1 : 0))
                            }
                            var nstr = new Date()
                            var ynow = nstr.getFullYear()
                            var mnow = nstr.getMonth()
                            var dnow = nstr.getDate()
                            var n1str = new Date(ynow, mnow, 1)

                            //判断当前是本学期第几周
                            var start_date = new Date(2018, 9, 10)
                            var today = new Date()
                            var end_date = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate())
                            var weeknum = Math.floor(((end_date - start_date) / 1000 / 60 / 60 / 24 + 1) / 7) + 1

                            //当月第一天是星期几
                            var firstday = n1str.getDay()

                            //各月份的总天数
                            var m_days = new Array(31, 28 + is_leap(ynow), 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)

                            //表格需要的行数
                            var tr_str = Math.ceil((m_days[mnow] + firstday) / 7)

                            $('.year').text(ynow + "年");
                            $('.month').text((mnow + 1) + "月");
                            $('.week').text(weeknum)
                            var tb_str;
                            for (i = 0; i < tr_str; i++) {
                                tb_str += "<tr>";
                                for (k = 0; k < 7; k++) {
                                    idx = i * 7 + k;
                                    date_str = idx - firstday + 1;
                                    (date_str <= 0 || date_str > m_days[mnow]) ? date_str = "&nbsp;" : date_str = idx - firstday + 1;
                                    date_str == dnow ? tb_str += "<td style='background-color: #007bff;color:white;'>" + date_str + "</td>" : tb_str += "<td>" + date_str + "</td>"
                                }
                                tb_str += "</tr>";
                            }
                            $('tbody').append(tb_str)
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form id="customer_ask">
                    <div class="form-group row">
                        <label for="lastname" class="col-md-2 col-form-label">联系人</label>
                    <div class="col-md-10">
                            <input type="text" class="form-control" id="lastname" name="c_name" placeholder="联系人姓名">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="telnum" class="col-12 col-md-2 col-form-label">联系电话</label>

                        <div class="col-md-10">
                            <input type="tel" class="form-control" id="telnum" name="c_tel" placeholder="电话号码">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="emailid" class="col-md-2 col-form-label">电子邮件</label>
                        <div class="col-md-10">
                            <input type="email" class="form-control" id="emailid" name="c_email" placeholder="电子邮箱">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="feedback" class="col-md-2 col-form-label">提交信息</label>
                        <div class="col-md-10">
                            <textarea class="form-control" id="feedback" name="messages" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="offset-md-2 col-md-10" id="errors" style="color:red;">

                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="offset-md-2 col-md-10">
                            <button type="button" id="btn_contact" class="btn btn-primary">联系我们</button>
                        </div>
                    </div>

                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
    <footer class="footer ">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center p-2" >
                    <p >@Copyright 2018-2020</p>
                    <p >洛阳师范学院电子商务学院 HQ开发组</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}
{% block domready %}
    <script>
        $(document).ready(function () {
            $('#btn_contact').click(function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'teacher:ask' %}",
                    data: $('#customer_ask').serialize(),
                    async: true,
                    success: function (data) {
                        if(data.status == 'success'){
                            $('#customer_ask')[0].reset();
                            alert("提交成功")
                        }else if(data.status == 'fail'){
                            $('#errors').html(data.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

teacher/templates/teacher/summaryscore.html
{% extends "base-4.1.1.html" %}
{% load static %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

{% endblock %}
{% block title %}
    成绩汇总
{% endblock %}

{% block content %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">洛师电商</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="Navbar">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'teacher:index' %}">
                            首页
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'teacher:coursetable' %}">
                            教师课表
                        </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'teacher:active' %}">
                            课堂活动
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'teacher:summary' %}">
                            成绩汇总
                        </a>
                    </li>
                </ul>
                <span class="navbar-text">
                    {% if request.user.is_authenticated %}
                        {{ request.user.username }},
                        <a data-toggle="modal" data-target="#loginModal">
                            退出
                        </a>
                    {% else %}
                    <a href="{% url 'teacher:login' %}">
                        登录
                    </a>
                    {% endif %}
                </span>
            </div>
        </div>
    </nav>
    <div id="loginModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg" role="content">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">退出登录</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'teacher:logout' %}" method="post">
                        <div class="form-group row">

                            <div class="col-sm-10">
                                <p>您将退出登录状态！</p>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12 d-flex justify-content-end">
                                <button type="button" class="btn btn-secondary btn-sm mr-3" data-dismiss="modal">取消</button>
                                <button type="submit" class="btn btn-primary btn-sm mr-3">确定</button>
                            </div>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <h3 class="card-header text-center">分课程按班级查看</h3>
                    <div class="card-body">
                        <h4 class="card-title">平时成绩汇总</h4>
                        <table class="table ">
                            <thead class="bg-primary text-white">
                            <tr>
                                <th scope="col">序号</th>
                                <th scope="col">班级</th>
                                <th scope="col">课程</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for ts in t_schedules %}
                                {% with banji_name=ts.banji__name course_name=ts.course__name %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td>{{ banji_name }}</td>
                                    <td>{{ course_name }}</td>
                                    <td><a href="{% url 'teacher:score' banji_name course_name %}">查看</a> </td>
                                </tr>
                                {% endwith %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="studentscore" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg" role="content">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">退出登录</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        &times;
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'teacher:logout' %}" method="post">
                        <div class="form-group row">

                            <div class="col-sm-10">
                                <p>{{ students }}</p>
                                <p>您将退出登录状态！</p>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-12 d-flex justify-content-end">
                                <button type="button" class="btn btn-secondary btn-sm mr-3" data-dismiss="modal">取消</button>
                                <button type="submit" class="btn btn-primary btn-sm mr-3">确定</button>
                            </div>
                        </div>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center p-2" >
                    <p >@Copyright 2018-2020</p>
                    <p >洛阳师范学院电子商务学院 HQ开发组</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}